### ISSUE TITLE
Error on validate google token

### ISSUE THREAD

**Issue by simpleway** [apigee/iloveapis2015-jwt-jwe-jws#4]
The google token validate endpoint
`curl -i -X POST http://apigee.mycomp.com/jwt_signed/validate-goog -d "jwt=eyJ....."`
throw the following error
` {
  "fault": {
    "faultstring": "Execution of JS-Extract-JWT-kid-for-Google failed with error: Javascript runtime error: \"ReferenceError: \"properties\" is not defined. (extractJwtKidForGoogle_js#72). at line 72 \"",
    "detail": {
      "errorcode": "steps.javascript.ScriptExecutionFailed"
    }
  }
}`
on on-premise apigee edge.

**Comment by DinoChiesa** [comment]
Hi - thanks for the report, and for mentioning that you are running the on-premises version of Apigee Edge. 
Last year, Apigee extended the Javascript policy to accept properties as input in the configuration file. If you look at the JS-Extract-JWT-kid-for-Google.xml policy configuration you will see properties there. 

But this capability was added after the release of the 15.07 OPDK. 
If you run this bundle on the 16.01 OPDK, it will work correctly.
I will update the Readme to note this.  
Sorry for the trouble. 
  is it possible you are running this The problem you are describing results from

**Comment by DinoChiesa** [comment]
The readme's have been updated
